version: '3.8'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest  # Usa a versão mais recente
    container_name: kafka-cluster
    restart: always  # Garante que o container reinicie automaticamente
    environment:
      ADV_HOST: 127.0.0.1  # Define o host como localhost
      RUNTESTS: 0          # Evita testes automáticos ao iniciar
      FORWARDLOGS: 0       # Reduz logs desnecessários
      SAMPLEDATA: 0        # Evita a criação automática de tópicos de exemplo
    ports:
      - "2181:2181"    # Zookeeper
      - "3030:3030"    # Kafka UI
      - "8081:8081"    # Schema Registry
      - "8082:8082"    # REST Proxy
      - "8083:8083"    # Kafka Connect
      - "9092:9092"    # Kafka Broker
      - "9581:9581"    # Monitoramento
      - "9582:9582"
      - "9583:9583"
      - "9584:9584"
      - "9585:9585"
    volumes:
      - kafka_data:/var/lib/kafka  # Persistência dos dados do Kafka

volumes:
  kafka_data:
    driver: local